# Generated by Django 4.2.28 on 2026-02-26 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('employee', 'Employee'), ('others', 'Others')], max_length=20)),
                ('department', models.CharField(max_length=255)),
                ('device_identifier', models.CharField(max_length=255)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event'], name='viewers_vie_event_i_0cea23_idx'), models.Index(fields=['email'], name='viewers_vie_email_2dbf00_idx')],
                'unique_together': {('email', 'device_identifier')},
            },
        ),
    ]
