# Generated by Django 4.2.28 on 2026-02-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewers', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible', models.BooleanField(default=False)),
                ('game_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('viewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viewers.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='RaffleWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('raffle_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raffle.raffleentry')),
            ],
        ),
        migrations.CreateModel(
            name='RaffleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('draw', 'Standard Draw'), ('game', 'Game-Based')], max_length=20)),
                ('min_booth_required', models.IntegerField(default=1)),
                ('game_threshold', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.AddIndex(
            model_name='raffleentry',
            index=models.Index(fields=['event'], name='raffle_raff_event_i_4e1f7b_idx'),
        ),
    ]
