# Generated by Django 4.2.28 on 2026-02-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffleentry',
            name='eligible',
        ),
    ]
