# Generated by Django 4.2.28 on 2026-02-27 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0002_remove_raffleentry_eligible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rafflewinner',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='rafflewinner',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
