# Generated by Django 4.2.28 on 2026-03-03 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('viewers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('memory', 'Memory Game'), ('word_shuffle', 'Word Shuffle'), ('quiz', 'Quiz'), ('reaction', 'Reaction Game')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('default_time_limit', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_limit_seconds', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('difficulty_order', models.IntegerField(default=1)),
                ('game_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameconfig')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('game_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameconfig')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamelevel')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('word', 'Word'), ('question', 'Question'), ('memory_pair', 'Memory Pair'), ('custom_data', 'Custom Data')], max_length=30)),
                ('data', models.JSONField()),
                ('points', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('game_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameconfig')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamelevel')),
            ],
        ),
        migrations.CreateModel(
            name='GameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('time_spent_seconds', models.IntegerField()),
                ('raw_answers', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamesession')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewers.viewer')),
            ],
            options={
                'unique_together': {('session', 'viewer')},
            },
        ),
    ]
