# Generated by Django 5.2.8 on 2026-03-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameattempt',
            name='fastest_correct_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
