# Generated by Django 4.2.28 on 2026-02-26 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exhibitors', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='exhibitors.exhibitor')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='viewers.viewer')),
            ],
            options={
                'indexes': [models.Index(fields=['event'], name='visits_visi_event_i_c27596_idx'), models.Index(fields=['viewer'], name='visits_visi_viewer__7dfbe2_idx'), models.Index(fields=['exhibitor'], name='visits_visi_exhibit_b2ec58_idx')],
                'unique_together': {('viewer', 'exhibitor')},
            },
        ),
    ]
